module.exports = {
  apps: [
    {
      name: 'lattice-master-daemon',
      script: 'scripts/master-daemon.mjs',
      interpreter: 'node',
      interpreter_args: '--import tsx',
      cwd: __dirname,
      autorestart: true,
      max_memory_restart: '1G',
      restart_delay: 5000,
      watch: false,
      kill_timeout: 10000,
      out_file: 'logs/daemon.out.log',
      error_file: 'logs/daemon.err.log',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'lattice-event-dashboard-api',
      script: 'scripts/event-dashboard-api.mjs',
      interpreter: 'node',
      interpreter_args: '--import tsx',
      cwd: __dirname,
      autorestart: true,
      max_memory_restart: '512M',
      restart_delay: 3000,
      watch: false,
      kill_timeout: 5000,
      out_file: 'logs/dashboard-api.out.log',
      error_file: 'logs/dashboard-api.err.log',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        DASHBOARD_PORT: 46200,
      },
    },
  ],
};
