/**
 * Sentry error filter lists, extracted from main.ts for maintainability.
 *
 * Organized by category so new patterns can be added to the appropriate group
 * rather than appended to an undifferentiated 250-entry array.
 */

// ── Browser extensions & injected scripts ────────────────────────────────
const BROWSER_EXTENSION_ERRORS: (string | RegExp)[] = [
  /Can.t find variable: (CONFIG|currentInset|NP|webkit|EmptyRanges|logMutedMessage|UTItemActionController|DarkReader|Readability|onPageLoaded|Game|frappe|getPercent|ucConfig|\$a)/,
  /DarkReader/,
  /GM_getValue/,
  /jQuery is not defined/,
  /detectIncognito/,
  /Cannot read properties of null \(reading '__uv'\)/,
  /Can't find variable: p\d+/,
  /ucapi is not defined/,
  /Cannot redefine property: webdriver/,
  /\$ is not defined/,
  /frappe is not defined/,
  /ucConfig is not defined/,
  /isReCreate is not defined/,
  /Can't find variable: caches/,
  /st_framedeep|ucbrowser_script/,
  /iabjs_unified_bridge/,
  /LibraryDetectorTests_detect/,
  /nmhCrx is not defined/,
  /SnapTube/,
  /window\.videoSniffer/,
  /closeTabMediaModal/,
  /hybridExecute is not defined/,
  /zaloJSV2/,
  /VConsole is not defined/,
  /WeixinJSBridge/,
  /[sx]wbrowser is not defined/,
  /browser\.storage\.local/,
  /orgSetInterval is not a function/,
  /window\.receiveMessage/,
  /window\.ethereum/,
  /__firefox__/,
  /SCDynimacBridge/,
  /errTimes is not defined/,
  /a2z\.onStatusUpdate/,
  /downProgCallback/,
  /syncDownloadState/,
  /hackLocationFailed is not defined/,
  /userScripts is not defined/,
  /trsMethod\w+ is not defined/,
  /checkLogin is not a function/,
  /zp_token is not defined/,
  /\bAutoReset\b/i,
  /^(?:LIDNotify(?:Id)?|onWebViewAppeared|onGetWiFiBSSID) is not defined$/,
  /navigationPerformanceLoggerJavascriptInterface/,
  /isWhiteToBlack/,
  /sortedTrackListForMenu/,
  /^ReferenceError: HTMLOUT is not defined$/,
  /^ReferenceError: xbrowser is not defined$/,
  /translateNotifyError/,
  /\bmag is not defined\b/,
  /_pcmBridgeCallbackHandler/,
  /UCShellJava/,
  /^\w{1,2} is not a function\. \(In '\w{1,2}\(/,
  /Can't find variable: video/,
  /Identifier '(?:script|reportPage|element)' has already been declared/,
  /getAttribute is not a function.*getAttribute\("role"\)/,
];

// ── WebGL / GPU rendering crashes ────────────────────────────────────────
const WEBGL_ERRORS: (string | RegExp)[] = [
  'Invalid WebGL2RenderingContext',
  'WebGL context lost',
  /Program failed to link/,
  /Could not compile fragment shader/,
  /Could not compile vertex shader/,
  /getShaderPrecisionFormat/,
  /maxTextureDimension2D/,
  /Failed to initialize WebGL/,
  /shaderSource must be an instance of WebGLShader/,
  /opacityVertexArray\.length/,
  /Length of new data is \d+, which doesn't match current length of/,
  /getProgramInfoLog/,
  /setting 'luma'/,
  /evaluating '[^']*\.luma/,
  /evaluating 'v\.setProps'/,
];

// ── Network / Fetch errors (transient) ───────────────────────────────────
const NETWORK_ERRORS: (string | RegExp)[] = [
  /^TypeError: Load failed( \(.*\))?$/,
  /^TypeError: Failed to fetch( \(.*\))?$/,
  /^TypeError: (?:cancelled|avbruten)$/,
  /^TypeError: NetworkError/,
  /^fetchError: Network request failed$/,
  /^AJAXError:.*(?:Load failed|Unauthorized|\(401\))/,
  /^NetworkError: Load failed$/,
  /^A network error occurred\.?$/,
  /Could not connect to the server/,
  /signal is aborted without reason/,
  /signal timed out/,
  /Fetch is aborted/,
  /(?:AbortError: )?The operation was aborted\.?\s*$/,
  /(?:AbortError: )?The user aborted a request/,
  /FetchEvent\.respondWith/,
  /^Operation timed out\.?$/,
  /Content-Length header of network response exceeds response Body/,
  /^TypeError: 已取消$/,
  /^timeout$/,
  /The fetching process for the media resource was aborted/,
  /The play\(\) request was interrupted/,
  /Error invoking postMessage: Java exception/,
];

// ── Module / Dynamic import failures ─────────────────────────────────────
const MODULE_ERRORS: (string | RegExp)[] = [
  /Failed to fetch dynamically imported module/,
  /Importing a module script failed/,
  /error loading dynamically imported module/,
  /importScripts/,
  /Unexpected end of script/,
  /Unexpected end of(?: JSON)? input/,
  /export declarations may only appear at top level/,
  /^SyntaxError: Unexpected keyword/,
  /^SyntaxError: Unexpected token/,
  /Unexpected identifier 'https'/,
  /Unexpected identifier 'does'/,
  /literal not terminated before end of script/,
  /Invalid character: '\\0'/,
  /missing \) after argument list/,
  /Invalid regular expression: missing/,
  /'' is not a valid selector/,
  /can't redefine non-configurable property/,
];

// ── Browser internal / platform errors ───────────────────────────────────
const PLATFORM_ERRORS: (string | RegExp)[] = [
  /imageManager/,
  /ResizeObserver loop/,
  /NotAllowedError/,
  /InvalidAccessError/,
  /NotSupportedError/,
  /QuotaExceededError/,
  /NS_ERROR_ABORT/,
  /NS_ERROR_OUT_OF_MEMORY/,
  /out of memory/,
  /Maximum call stack size exceeded/,
  /too much recursion/,
  /^Key not found$/,
  /Array buffer allocation failed/,
  /IndexSizeError/,
  /DataCloneError.*could not be cloned/,
  /Fullscreen request denied/,
  /requestFullscreen/,
  /webkitEnterFullscreen/,
  /webkitExitFullScreen/,
  /exitFullscreen.*Document not active/,
  /releasePointerCapture.*Invalid pointer/,
  /Failed to execute 'unobserve' on 'IntersectionObserver'/,
  /WKErrorDomain/,
  /^Uncaught \[object ErrorEvent\]$/,
  /Force close delete origin/,
  /^InvalidStateError:|The object is in an invalid state/,
  /Connection to Indexed Database server lost/,
  /createObjectStore/,
  /objectStoreNames/,
  /The database connection is closing/,
  /Failed reading data from the file system/,
  /Failed writing data to the file system/,
  /^UnavailableError(:.*)?$/,
  /Failed to get ServiceWorkerRegistration/,
  /^ReferenceError: Cannot access uninitialized variable\.?$/,
  /crypto\.randomUUID is not a function/,
  /Cannot define multiple custom elements/,
  /Attempting to change value of a readonly property/,
  /Attempted to assign to readonly property/,
  /Cannot assign to read only property/,
  /Cannot add property \w+, object is not extensible/,
  /Cannot redefine property: userAgent/,
  /MutationEvent is not defined/,
  /Stylesheet append timeout/,
  /Worker is not a constructor/,
  /Failed to construct 'Worker'.*cannot be accessed from origin/,
  /Style is not done loading/,
  /reading 'nodeType'/,
  /feature named .\w+. was not found/,
  /^TypeError: Internal error$/,
  /contentBoxSize\[0\] is undefined/,
  /Out of range source coordinates for DEM data/,
  /Attempting to run\(\), but is already running/,
  /Policy with name .* already exists/,
  /Client can't handle this message/,
  /Invalid LngLat object/,
  /Cannot read properties of null \(reading 'touches'\)/,
  /Failed to execute 'querySelectorAll' on '[^']*': ':[a-z]+\(/,
  /can't access property "\w+", FONTS\[/,
  /args\.site\.enabledFeatures/,
];

// ── WebView / Mobile bridge errors ───────────────────────────────────────
const WEBVIEW_ERRORS: (string | RegExp)[] = [
  /webkit\.messageHandlers/,
  /runtime\.sendMessage\(\)/,
  /Java object is gone/,
  /Java bridge method invocation error/,
  /contentWindow\.postMessage/,
  /WKWebView was deallocated/,
  /window\.android\.\w+ is not a function/,
  /reading 'postMessage'/,
  /Blocked a frame with origin.*accessing a cross-origin frame/,
  /Error invoking initializeCallbackHandler/,
  /webkitCurrentPlaybackTargetIsWireless/,
  /webkit(?:Supports)?PresentationMode/,
  /this\.player\.\w+ is not a function/,
  /this\.player\.destroy is not a function/,
  /reading 'style'.*HTMLImageElement/,
  /can't access property "write", \w+ is undefined/,
  /Cross-origin script load denied/,
  /^Object captured as promise rejection with keys:/,
  /Non-Error promise rejection captured with value:/,
  /Event `CustomEvent`.*captured as promise rejection/,
  /(?:unsafe-eval.*Content Security Policy|Content Security Policy.*unsafe-eval)/,
  /vc_text_indicators_context/,
  /invalid origin/,
  /\.data\.split is not a function/,
  /appendChild.*Unexpected token/,
  /e\.toLowerCase is not a function/,
  /\.trim is not a function/,
  /\.(indexOf|findIndex) is not a function/,
  /cannot decode message/,
  /videoTrack\.configuration/,
  /button\[aria-label/,
  /shortcut icon/,
  /evaluating 'elemFound\.value'/,
  /[Cc]an(?:'t|not) access (?:'\w+'|lexical declaration '\w+') before initialization/,
  /^Uint8Array$/,
  /null is not an object \(evaluating '\w{1,3}\.indexOf'\)/,
  /Qt\([^)]*\) is not a function/,
  /^\w{1,2} is null$/,
  /illegal UTF-16 sequence/,
  /ifameElement\.contentDocument/,
];

// ── Third-party widget / media errors ────────────────────────────────────
const THIRD_PARTY_ERRORS: (string | RegExp)[] = [
  /Unable to load image/,
  /Invalid video id/,
  /Se requiere plan premium/,
  /ML request .* timed out/,
  /^Element not found$/,
  /Container app not found/,
  /this\.St\.unref/,
  /Invalid or unexpected token/,
  /undefined is not an object \(evaluating '\w+\.(?:type|pathType|count|__globeObjType)'\)/,
  /null is not an object \(evaluating '\w+\.__globeObjType'\)/,
  /parentNode\.insertBefore/,
  /Could not establish connection\. Receiving end does not exist/,
];

/**
 * All Sentry `ignoreErrors` patterns, merged from categorized groups.
 */
export const SENTRY_IGNORE_ERRORS: (string | RegExp)[] = [
  ...BROWSER_EXTENSION_ERRORS,
  ...WEBGL_ERRORS,
  ...NETWORK_ERRORS,
  ...MODULE_ERRORS,
  ...PLATFORM_ERRORS,
  ...WEBVIEW_ERRORS,
  ...THIRD_PARTY_ERRORS,
];
